# Generated by Django 5.0.7 on 2024-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='return_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='return_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
