# Generated by Django 5.0.7 on 2024-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typetest', '0004_remove_type_user_type_content_alter_type_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='typetest/'),
        ),
    ]
