# Generated by Django 5.0.7 on 2024-08-01 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_information', '0022_comment_created_at_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_day', models.DateTimeField(auto_now_add=True)),
                ('heart', models.BooleanField(default=True)),
                ('comment', models.BooleanField(default=True)),
                ('point', models.BooleanField(default=True)),
                ('hue', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('HEART', '하트'), ('POINT', '포인트'), ('COMMENT', '댓글'), ('PROMOTE', '홍보')], max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('small_content', models.TextField(blank=True, null=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='review_information.information')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='review_information.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
