# Generated by Django 5.0.7 on 2024-08-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_news_where_news_who_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='who',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
