# Generated by Django 5.0.7 on 2024-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_news_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart', models.BooleanField(default=True)),
                ('comment', models.BooleanField(default=True)),
                ('point', models.BooleanField(default=True)),
                ('hue', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='news',
            name='hue',
        ),
        migrations.RemoveField(
            model_name='news',
            name='point',
        ),
    ]
