# Generated by Django 5.0.7 on 2024-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_alter_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsoption',
            name='not_read',
            field=models.BooleanField(default=True),
        ),
    ]
