# Generated by Django 5.0.7 on 2024-07-27 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bingo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('large_category', models.CharField(choices=[('CAREER', '채용'), ('CERTIFICATE', '자격증'), ('OUTBOUND', '대외활동'), ('CONTEST', '공모전'), ('HOBBY', '취미'), ('TRAVEL', '여행'), ('SELFIMPROVEMENT', '자기계발'), ('REST', '휴식')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('large_category', models.CharField(choices=[('CAREER', '채용'), ('CERTIFICATE', '자격증'), ('OUTBOUND', '대외활동'), ('CONTEST', '공모전'), ('HOBBY', '취미'), ('TRAVEL', '여행'), ('SELFIMPROVEMENT', '자기계발'), ('REST', '휴식')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField()),
                ('bingo_space', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bingo.bingospace')),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bingo.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='information/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_images', to='review_information.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='review_information.review')),
            ],
        ),
    ]
