# Generated by Django 5.0.7 on 2024-07-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0002_alter_informationimage_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='review_information.information'),
        ),
    ]
