# Generated by Django 5.0.7 on 2024-07-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0003_alter_informationimage_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationimage',
            old_name='review',
            new_name='Information',
        ),
    ]
