# Generated by Django 5.0.7 on 2024-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0004_rename_review_informationimage_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
