# Generated by Django 5.0.7 on 2024-07-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0005_alter_information_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationimage',
            old_name='Information',
            new_name='information',
        ),
    ]
