# Generated by Django 5.0.7 on 2024-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0008_alter_information_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='app_due',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='app_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='duty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='employment_form',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='field',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='host',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='prep_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='work_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
