# Generated by Django 5.0.7 on 2024-07-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_alter_todo_bingo_space'),
        ('review_information', '0009_review_app_due_review_app_fee_review_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.todo'),
        ),
    ]
