# Generated by Django 5.0.7 on 2024-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0010_review_procedure_alter_review_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='prep_period',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='app_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
