# Generated by Django 5.0.7 on 2024-07-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_alter_custombingoitem_prep_period_and_more'),
        ('review_information', '0011_remove_review_prep_period_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.todo'),
        ),
        migrations.CreateModel(
            name='DetailPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='review_information.review')),
            ],
        ),
    ]
