# Generated by Django 5.0.7 on 2024-07-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0012_alter_review_todo_detailplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='work_period',
        ),
    ]
