# Generated by Django 5.0.7 on 2024-07-29 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0016_alter_reviewimage_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_informaion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='information',
            name='storage',
            field=models.ManyToManyField(blank=True, related_name='storage_information', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='storage',
            field=models.ManyToManyField(blank=True, related_name='storage_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
