# Generated by Django 5.0.7 on 2024-07-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0019_alter_comment_author_alter_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='todo',
        ),
    ]
