# Generated by Django 5.0.7 on 2024-07-31 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0020_remove_review_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
