# Generated by Django 5.0.7 on 2024-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0024_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
