# Generated by Django 5.0.7 on 2024-08-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_information', '0027_information_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
