# Generated by Django 5.0.7 on 2024-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verif_code', models.CharField(max_length=6)),
                ('hash', models.CharField(max_length=20, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
            ],
        ),
    ]
