# Generated by Django 5.0.7 on 2024-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verif',
            name='hash',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
