# Generated by Django 5.0.7 on 2024-07-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_birth_alter_customuser_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
