# Generated by Django 5.0.7 on 2024-07-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_phone_number'),
        ('users', '0005_alter_customuser_is_active'),
    ]

    operations = [
    ]
