# Generated by Django 5.0.7 on 2024-07-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_first_name_and_more'),
        ('users', '0007_customuser_type_result'),
    ]

    operations = [
    ]
