# Generated by Django 5.0.7 on 2024-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20240726_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verif',
            name='school',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
