# Generated by Django 5.0.7 on 2024-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingospace',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bingospace',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
