# Generated by Django 5.0.7 on 2024-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_bingospace_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bingospace',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bingospace',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
