# Generated by Django 5.0.7 on 2024-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_bingospace_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombingoitem',
            name='large_category',
            field=models.CharField(choices=[('CAREER', '채용'), ('CERTIFICATE', '자격증'), ('OUTBOUND', '대외활동'), ('CONTEST', '공모전'), ('HOBBY', '취미'), ('TRAVEL', '여행'), ('SELFIMPROVEMENT', '자기계발'), ('REST', '휴식')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providedbingoitem',
            name='large_category',
            field=models.CharField(choices=[('CAREER', '채용'), ('CERTIFICATE', '자격증'), ('OUTBOUND', '대외활동'), ('CONTEST', '공모전'), ('HOBBY', '취미'), ('TRAVEL', '여행'), ('SELFIMPROVEMENT', '자기계발'), ('REST', '휴식')], max_length=20),
        ),
    ]
