# Generated by Django 5.0.7 on 2024-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_alter_todo_bingo_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingospace',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
