# Generated by Django 5.0.7 on 2024-07-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_start_date_alter_bingospace_end_date_and_more'),
        ('bingo', '0005_bingospace_date'),
    ]

    operations = [
    ]
