# Generated by Django 5.0.7 on 2024-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_merge_20240728_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombingoitem',
            name='prep_period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='providedbingoitem',
            name='prep_period',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
