# Generated by Django 5.0.7 on 2024-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_providedbingoitem_is_notice_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
