# Generated by Django 5.0.7 on 2024-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_notice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='ProvidedBingoItem',
            new_name='provided_bingo_item',
        ),
    ]
