# Generated by Django 5.0.7 on 2024-08-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_rename_providedbingoitem_notice_provided_bingo_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_school', models.DateField(blank=True, null=True)),
                ('rest_school_dday', models.CharField(default='휴학 D-?', max_length=15)),
                ('return_school', models.DateField(blank=True, null=True)),
                ('return_school_dday', models.CharField(default='복학 D-?', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
