# Generated by Django 5.0.7 on 2024-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0014_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateField(editable=False),
        ),
    ]
